name: Dl image
on:
  push:
    branches:
      - test

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download image
        run: wget --no-check-certificate "https://drive.usercontent.google.com/download?id=1qkruX6N1Lp6KQivwoP-aNBEoLIHIWBuN&confirm=t" -O "image.jpg"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Create output folder
        run: mkdir -p output
      - name: Transform image
        run: go run converter.go
      - name: ls
        run: ls -lh output
