name: Download and update image
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Download image
        run: wget --no-check-certificate "https://drive.usercontent.google.com/download?id=1qkruX6N1Lp6KQivwoP-aNBEoLIHIWBuN&confirm=t" -O "image.jpg"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Transform image
        run: go run converter.go
      - name: Remove base image
        run: rm ./image.jpg
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: update spread image
